env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  import/no-named-as-default: 0
  import/no-named-as-default-member: 0
